name: Build and Deploy Django App to EC2

on:
  push:
    branches:
      - main
    paths:
      - '**'  # Optional: Only trigger if relevant files change

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
    - name: Show files and Dockerfile details
      run: |
        ls -al
        file Dockerfile || echo "Dockerfile missing"

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/django-app:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/django-app:latest

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Install Docker on EC2 and run container
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Install Docker if not installed
          if ! command -v docker &> /dev/null; then
            sudo dnf update -y
            sudo dnf install -y docker
            sudo systemctl enable docker
            sudo systemctl start docker
          fi

          # Stop old container if running
          docker stop django-app || true
          docker rm django-app || true

          # Pull latest Docker image
          docker pull ${{ secrets.DOCKER_USERNAME }}/django-app:latest

          # Run new container
          docker run -d \
            --name django-app \
            -p 8000:8000 \
            ${{ secrets.DOCKER_USERNAME }}/django-app:latest
        EOF
